package api

import "testing"

func TestShouldRetryWithHeuristicPlan(t *testing.T) {
	plannerWarnings := []string{"SQL was generated by the configured LLM provider."}
	result := queryExecutionResult{
		OK:    false,
		Error: "Error: in prepare, no such column: revenue_total",
	}

	if !shouldRetryWithHeuristicPlan(plannerWarnings, result) {
		t.Fatalf("expected heuristic retry to be enabled for repairable LLM SQL errors")
	}
}

func TestShouldNotRetryWithoutLLMWarning(t *testing.T) {
	result := queryExecutionResult{
		OK:    false,
		Error: "Error: in prepare, no such column: revenue_total",
	}

	if shouldRetryWithHeuristicPlan(nil, result) {
		t.Fatalf("expected heuristic retry to stay disabled without LLM-generated SQL")
	}
}

func TestShouldNotRetryForNonRepairableErrors(t *testing.T) {
	plannerWarnings := []string{"SQL was generated by the configured LLM provider."}
	result := queryExecutionResult{
		OK:    false,
		Error: "database is locked",
	}

	if shouldRetryWithHeuristicPlan(plannerWarnings, result) {
		t.Fatalf("expected heuristic retry to stay disabled for non-repairable errors")
	}
}
